#----------------------------------------
# GENERAL SETTINGS
#----------------------------------------

# Site title, appears in the browser tab.
title: "Miczał"

# Site description in search engine.
description: "Simple portfolio-showcase Jekyll theme."

# Language settings for html and seo
lang: "en_GB"
iso-lang: "en"

# Production url.
url: "https://themiczal.github.io"

# Part after .com, etc. use / if none.
baseurl: /



#----------------------------------------
# CONTENT VARIABLES
#----------------------------------------

# Appears in first section and footer
owner: "Miczał"

# Navbar links
nav_sites:
  -
    link: "https://www.instagram.com/miczal_/"
    icon: icon-instagram
  -
    link: "https://www.youtube.com/channel/UC1-vE37Wb2sxfGgXYFsQhjw"
    icon: icon-youtube
  -
    link: "https://www.linkedin.com/in/micha%C5%82-urba%C5%84ski-870706174"
    icon: icon-linkedin

# Main content
header: Hi.</br>I'm&nbsp;Miczał
headerParagraph: Art speaks where words are unable to explain.
indexParagraph1: I'm an aspiring graphic designer. I do <a href="#drawings">Drawings</a>, <a href="#conceptart">Concept Art</a>, <a href="#posters">Posters</a> and even some <a href="#programming">Programming</a>!
indexParagraph2: I'm 23 years old, I like to draw, play games and watch stars at night. <(･ω･´)>

# Carousel images paths
images:
  -
    full: "/assets/img/slider1"
    min: "/assets/img/slider1"
  -
    full: "/assets/img/slider2"
    min: "/assets/img/slider2"


sections:
  -
    title: Drawings
    id: drawings
    video: false
    paragraph: I'm drawing for few years now. Style of my drawings, is mainly anime-like, but I like to experiment with other styles.
    images:
      -
        full: "/assets/img/Drawings1_full"
        min: "/assets/img/Drawings1_small"
      -
        full: "/assets/img/Drawings2_full"
        min: "/assets/img/Drawings2_small"
      -
        full: "/assets/img/Drawings3_full"
        min: "/assets/img/Drawings3_small"
      -
        full: "/assets/img/Drawings4_full"
        min: "/assets/img/Drawings4_small"
      -
        full: "/assets/img/Drawings5_full"
        min: "/assets/img/Drawings5_small"
      -
        full: "/assets/img/Drawings6_full"
        min: "/assets/img/Drawings6_small"
      -
        full: "/assets/img/Drawings7_full"
        min: "/assets/img/Drawings7_small"
      -
        full: "/assets/img/Drawings8_full"
        min: "/assets/img/Drawings8_small"
      -
        full: "/assets/img/Drawings9_full"
        min: "/assets/img/Drawings9_small"
  -
    title: Posters
    id: posters
    video: false
    paragraph: I was mainly doing posters for my middle school. I was main artist for Festival of Technical Talents in my school for three years.
    images:
      -
        full: "/assets/img/Posters1_full"
        min: "/assets/img/Posters1_small"
      -
        full: "/assets/img/Posters2_full"
        min: "/assets/img/Posters2_small"
      -
        full: "/assets/img/Posters3_full"
        min: "/assets/img/Posters3_small"
      -
        full: "/assets/img/Posters4_full"
        min: "/assets/img/Posters4_small"
      -
        full: "/assets/img/Posters5_full"
        min: "/assets/img/Posters5_small"
  -
    title: Programming
    id: programming
    video: false
    paragraph: Im mainly interested in Graphic Design, but also I like programming. I know basics of AHK, C++ and Java but mainly I`m programming in Python. Right now im working on indie game called <a href="https://themiczal.github.io/TaleofWitchsHeart/">Tale of Witch's Heart</a>
    images:
      -
        full: "/assets/img/screen0"
        min: "/assets/img/screen0"
      -
        full: "/assets/img/screen1"
        min: "/assets/img/screen1"
      -
        full: "/assets/img/screen2"
        min: "/assets/img/screen2"
      -
        full: "/assets/img/screen3"
        min: "/assets/img/screen3"
      -
        full: "/assets/img/screen4"
        min: "/assets/img/screen4"
      -
        full: "/assets/img/screen5"
        min: "/assets/img/screen5"
      -
        full: "/assets/img/screen6"
        min: "/assets/img/screen6"
      -
        full: "/assets/img/screen7"
        min: "/assets/img/screen7"
      -
        full: "/assets/img/screen8"
        min: "/assets/img/screen8"
      -
        full: "/assets/img/screen9"
        min: "/assets/img/screen9"
      -
        full: "/assets/img/screen10"
        min: "/assets/img/screen10"
      -
        full: "/assets/img/screen11"
        min: "/assets/img/screen11"
      -
        full: "/assets/img/screen12"
        min: "/assets/img/screen12"
      -
        full: "/assets/img/screen13"
        min: "/assets/img/screen13"
      -
        full: "/assets/img/screen14"
        min: "/assets/img/screen14"
      -
        full: "/assets/img/screen15"
        min: "/assets/img/screen15"


# Footer content - please edit the _includes/footer.html file.



#----------------------------------------
# JEKYLL SETTINGS
#----------------------------------------

# Takes files from root folder, generates site into ./_site.
source: .
destination: ./_site

# Default variables for pages. Are in use if not overwritten.
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Excluding dev gem builds from website.
exclude: [vendor]

# Jekyll plugins.
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
