#----------------------------------------
# GENERAL SETTINGS
#----------------------------------------

# Site title, appears in the browser tab.
title: "Miczał"

# Site description in search engine.
description: "Simple portfolio-showcase Jekyll theme."

# Language settings for html and seo
lang: "en_GB"
iso-lang: "en"

# Production url.
url: "https://themiczal.github.io"

# Part after .com, etc. use / if none.
baseurl: /



#----------------------------------------
# CONTENT VARIABLES
#----------------------------------------

# Appears in first section and footer
owner: "Miczał"

# Navbar links
nav_sites:
  -
    link: "https://www.instagram.com/miczal_/"
    icon: icon-instagram
  -
    link: "https://www.youtube.com/channel/UC1-vE37Wb2sxfGgXYFsQhjw"
    icon: icon-youtube
  -
    link: "https://www.linkedin.com/in/micha%C5%82-urba%C5%84ski-870706174"
    icon: icon-linkedin

# Main content
header: Hi.</br>I'm&nbsp;Miczał
headerParagraph: Art speaks where words are unable to explain.
indexParagraph1: I'm an aspiring graphic designer. I do <a href="#drawings">Drawings</a>, <a href="#conceptart">Concept Art</a>, <a href="#posters">Posters</a> and even some <a href="#programming">Programming</a>!
indexParagraph2: I'm 23 years old, I like to draw, play games and watch stars at night. <(･ω･´)>
indexParagraph3: Digital artist and programming instructor, currently developing <a href="https://themiczal.github.io/TaleofWitchsHeart/">Tale of Witch's Heart</a>. Contact: <a href="mailto:themiczal@gmail.com">themiczal@gmail.com</a>.

# Carousel images paths
images:
  -
    full: "/assets/img/slider0"
    min: "/assets/img/slider0"
  -
    full: "/assets/img/slider22"
    min: "/assets/img/slider22"
  -
    full: "/assets/img/slider17"
    min: "/assets/img/slider17"
  -
    full: "/assets/img/slider16"
    min: "/assets/img/slider16"
  -
    full: "/assets/img/slider3"
    min: "/assets/img/slider3"
  -
    full: "/assets/img/slider4"
    min: "/assets/img/slider4"
  -
    full: "/assets/img/slider5"
    min: "/assets/img/slider5"
  -
    full: "/assets/img/slider6"
    min: "/assets/img/slider6"
  -
    full: "/assets/img/slider7"
    min: "/assets/img/slider7"
  -
    full: "/assets/img/slider8"
    min: "/assets/img/slider8"
  -
    full: "/assets/img/slider9"
    min: "/assets/img/slider9"
  -
    full: "/assets/img/slider10"
    min: "/assets/img/slider10"
  -
    full: "/assets/img/slider12"
    min: "/assets/img/slider12"
  -
    full: "/assets/img/slider11"
    min: "/assets/img/slider11"
  -
    full: "/assets/img/slider13"
    min: "/assets/img/slider13"
  -
    full: "/assets/img/slider14"
    min: "/assets/img/slider14"
  -
    full: "/assets/img/slider15"
    min: "/assets/img/slider15"
  -
    full: "/assets/img/slider18"
    min: "/assets/img/slider18"
  -
    full: "/assets/img/slider20"
    min: "/assets/img/slider20"
  -
    full: "/assets/img/slider21"
    min: "/assets/img/slider21"
  -
    full: "/assets/img/slider1"
    min: "/assets/img/slider1"
  -
    full: "/assets/img/slider23"
    min: "/assets/img/slider23"
  -
    full: "/assets/img/slider24"
    min: "/assets/img/slider24"


sections:
  -
    title: Drawings
    id: drawings
    video: false
    paragraph: I'm drawing for few years now. Style of my drawings, is mainly anime-like, but I like to experiment with other styles.
    images:
      -
        full: "/assets/img/art32"
        min: "/assets/img/art32"
      -
        full: "/assets/img/art0"
        min: "/assets/img/art0"
      -
        full: "/assets/img/art1"
        min: "/assets/img/art1"
      -
        full: "/assets/img/art2"
        min: "/assets/img/art2"
      -
        full: "/assets/img/art3"
        min: "/assets/img/art3"
      -
        full: "/assets/img/art4"
        min: "/assets/img/art4"
      -
        full: "/assets/img/art5"
        min: "/assets/img/art5"
      -
        full: "/assets/img/art6"
        min: "/assets/img/art6"
      -
        full: "/assets/img/art7"
        min: "/assets/img/art7"
      -
        full: "/assets/img/art8"
        min: "/assets/img/art8"
      -
        full: "/assets/img/art9"
        min: "/assets/img/art9"
      -
        full: "/assets/img/art10"
        min: "/assets/img/art10"
      -
        full: "/assets/img/art11"
        min: "/assets/img/art11"
      -
        full: "/assets/img/art12"
        min: "/assets/img/art12"
      -
        full: "/assets/img/art13"
        min: "/assets/img/art13"
      -
        full: "/assets/img/art14"
        min: "/assets/img/art14"
      -
        full: "/assets/img/art16"
        min: "/assets/img/art16"
      -
        full: "/assets/img/art17"
        min: "/assets/img/art17"
      -
        full: "/assets/img/art18"
        min: "/assets/img/art18"
      -
        full: "/assets/img/art19"
        min: "/assets/img/art19"
      -
        full: "/assets/img/art20"
        min: "/assets/img/art20"
      -
        full: "/assets/img/art21"
        min: "/assets/img/art21"
      -
        full: "/assets/img/art22"
        min: "/assets/img/art22"
      -
        full: "/assets/img/art23"
        min: "/assets/img/art23"
      -
        full: "/assets/img/art24"
        min: "/assets/img/art24"
      -
        full: "/assets/img/art25"
        min: "/assets/img/art25"
      -
        full: "/assets/img/art28"
        min: "/assets/img/art28"
      -
        full: "/assets/img/art29"
        min: "/assets/img/art29"
      -
        full: "/assets/img/art31a"
        min: "/assets/img/art31a"
      -
        full: "/assets/img/art31b"
        min: "/assets/img/art31b"
      -
        full: "/assets/img/art31c"
        min: "/assets/img/art31c"
      -
        full: "/assets/img/art26"
        min: "/assets/img/art26"
      -
        full: "/assets/img/art27"
        min: "/assets/img/art27"
      -
        full: "/assets/img/art30"
        min: "/assets/img/art30"
  -
    title: Posters and Flyers
    id: posters
    video: false
    paragraph: I was mainly doing posters and Flyers for my middle school. I was main artist for Festival of Technical Talents in my school for three years.
    images:
      -
        full: "/assets/img/Posters1_full"
        min: "/assets/img/Posters1_small"
      -
        full: "/assets/img/Posters2_full"
        min: "/assets/img/Posters2_small"
      -
        full: "/assets/img/Posters3_full"
        min: "/assets/img/Posters3_small"
      -
        full: "/assets/img/Posters4_full"
        min: "/assets/img/Posters4_small"
      -
        full: "/assets/img/Posters5_full"
        min: "/assets/img/Posters5_small"
      -
        full: "/assets/img/Posters6_full"
        min: "/assets/img/Posters6_small"
      -
        full: "/assets/img/Posters7_full"
        min: "/assets/img/Posters7_small"
      -
        full: "/assets/img/Posters8_full"
        min: "/assets/img/Posters8_small"
      -
        full: "/assets/img/Posters9_full"
        min: "/assets/img/Posters9_small"
      -
        full: "/assets/img/Posters10_full"
        min: "/assets/img/Posters10_small"
  -
    title: Programming
    id: programming
    video: false
    paragraph: Im mainly interested in Graphic Design, but also I like programming. I know basics of AHK, C++ and Java but mainly I`m programming in Python. Right now im working on indie game called <a href="https://themiczal.github.io/TaleofWitchsHeart/">Tale of Witch's Heart.</a> You can check <a href="https://www.youtube.com/@taleofwitchsheart">Devlog</a> here!
    images:
      -
        full: "/assets/img/screen0"
        min: "/assets/img/screen0"
      -
        full: "/assets/img/screen1"
        min: "/assets/img/screen1"
      -
        full: "/assets/img/screen2"
        min: "/assets/img/screen2"
      -
        full: "/assets/img/screen3"
        min: "/assets/img/screen3"
      -
        full: "/assets/img/screen4"
        min: "/assets/img/screen4"
      -
        full: "/assets/img/screen5"
        min: "/assets/img/screen5"
      -
        full: "/assets/img/screen6"
        min: "/assets/img/screen6"
      -
        full: "/assets/img/screen7"
        min: "/assets/img/screen7"
      -
        full: "/assets/img/screen8"
        min: "/assets/img/screen8"
      -
        full: "/assets/img/screen9"
        min: "/assets/img/screen9"
      -
        full: "/assets/img/screen10"
        min: "/assets/img/screen10"
      -
        full: "/assets/img/screen11"
        min: "/assets/img/screen11"
      -
        full: "/assets/img/screen12"
        min: "/assets/img/screen12"
      -
        full: "/assets/img/screen13"
        min: "/assets/img/screen13"
      -
        full: "/assets/img/screen14"
        min: "/assets/img/screen14"
      -
        full: "/assets/img/screen15"
        min: "/assets/img/screen15"
  -
    title: Past Projects
    id: past
    video: true
    paragraph: Many years ago i did some other games. They were games made for one friend who is streamer. This was basically one giant meme.
    images:
      -
        full: "/assets/img/Bs2_Trailer1.webm"
      -
        full: "/assets/img/Bs2_Trailer2.webm"

# Footer content - please edit the _includes/footer.html file.



#----------------------------------------
# JEKYLL SETTINGS
#----------------------------------------

# Takes files from root folder, generates site into ./_site.
source: .
destination: ./_site

# Default variables for pages. Are in use if not overwritten.
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Excluding dev gem builds from website.
exclude: [vendor]

# Jekyll plugins.
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
